---
name: Main Workflow
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - name: Test
        run: go test ./...
