---
name: Master Workflow
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - name: Test
        run: go test ./... -v -coverprofile=coverage.txt -covermode count
      - name: Get coverage
        run: echo "COVERAGE=$(go tool cover -func coverage.txt | tail -1 | awk '{print $3}')" >> $GITHUB_ENV
      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 03d07927044bdfe73aee59e6193dd8d5
          filename: badge-coverage-semangit.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          valColorRange: ${{ env.COVERAGE }}
          maxColorRange: 100
          minColorRange: 0
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - name: Build
        run: go build -o semangit .
      - name: Smoke test
        run: ./semangit --help
      - uses: actions/upload-artifact@v3
        with:
          name: semangit
          path: semangit
