---
name: Tags Workflow
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - name: Build
        run: go build -o semangit .
      - name: Smoke test
        run: ./semangit --help
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: semangit
