---
name: Tags Workflow
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - name: Build
        run: go build -o semangit .
      - name: Smoke test
        run: ./semangit --help
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: semangit
      - uses: actions/upload-artifact@v3
        with:
          name: semangit
          path: semangit
  release-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: semangit
          path: semangit
      - run: docker build -t semangit:$GITHUB_REF_NAME .
      - run: echo "TODO:\ Push the image to DockerHub"